# Generated by Django 4.0.4 on 2022-04-17 07:22

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.IntegerField(max_length=100, primary_key=sqlalchemy.sql.expression.true, serialize=False, unique=True)),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Email', models.EmailField(max_length=50)),
                ('contact_number', models.IntegerField(max_length=100)),
            ],
        ),
    ]
