# Generated by Django 4.0.4 on 2022-04-17 07:26

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('EBikeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserId',
            field=models.IntegerField(primary_key=sqlalchemy.sql.expression.true, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
