# Generated by Django 4.0.4 on 2022-04-17 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EBikeApp', '0004_alter_user_userid_alter_user_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('batteryID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('batteryTYPE', models.CharField(max_length=10)),
                ('Watthour', models.IntegerField(max_length=10)),
                ('lifetime', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('inverterID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Wattage', models.IntegerField(max_length=10)),
                ('volts', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('motorID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('motorTYPE', models.CharField(max_length=10)),
                ('placement', models.CharField(max_length=10)),
                ('Wattage', models.IntegerField(max_length=10)),
                ('volts', models.IntegerField(max_length=10)),
                ('manufacturer', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('structureID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('frame', models.CharField(max_length=10)),
                ('payloadCAP', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleTYPE', models.CharField(max_length=10)),
                ('weightKG', models.IntegerField(default=0)),
                ('OrderDATE', models.DateTimeField()),
                ('warrantyDATE', models.DateTimeField()),
                ('tyre', models.CharField(max_length=10)),
                ('helmet', models.CharField(max_length=10)),
                ('pedal', models.CharField(max_length=10)),
                ('meter', models.CharField(max_length=10)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='EBikeApp.battery')),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='EBikeApp.inverter')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='EBikeApp.motor')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='EBikeApp.structure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='EBikeApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewTEXT', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='EBikeApp.user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='EBikeApp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='billingdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=15)),
                ('zip', models.IntegerField(default=0)),
                ('CCno', models.IntegerField(default=0)),
                ('promocode', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='EBikeApp.user')),
            ],
        ),
    ]
