# Generated by Django 4.0.4 on 2022-04-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBikeApp', '0006_alter_battery_watthour_alter_battery_lifetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='Watthour',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='battery',
            name='lifetime',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='CCno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='zip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='Wattage',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='volts',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='motor',
            name='Wattage',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='motor',
            name='volts',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='structure',
            name='payloadCAP',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='weightKG',
            field=models.IntegerField(default=0),
        ),
    ]
