# Generated by Django 4.0.4 on 2022-04-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBikeApp', '0007_alter_battery_watthour_alter_battery_lifetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='Watthour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battery',
            name='lifetime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motor',
            name='Wattage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motor',
            name='volts',
            field=models.IntegerField(default=0),
        ),
    ]
