# Generated by Django 4.0.4 on 2022-04-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBikeApp', '0009_battery_volts'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='color',
            field=models.CharField(default='red', max_length=10),
        ),
    ]
